### ISSUE TITLE
workflows

### ISSUE THREAD

**Issue by 99003152** [99003152/calculator_miniproject#12]
workflows except cpp-check are not getting initiated. give a look @99003151 and @Haritha1999

**Comment by Haritha1999** [comment]
> workflows except cpp-check are not getting initiated. give a look @99003151 and @Haritha1999

Try changing the branch

**Comment by Haritha1999** [comment]
The arithmetic operations program is showing some errors. can you please look into it @99003151  and @99003152

**Comment by 99003152** [comment]
> > workflows except cpp-check are not getting initiated. give a look @99003151 and @Haritha1999
> 
> Try changing the branch

i changed master branch to main and its working. thank you.
